security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider

    # Access control
    access_control:
        # Routes publiques
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        
        # Lecture des produits - utilisateurs connectés
        - { path: ^/api/produits$, roles: ROLE_USER, methods: [GET] }
        - { path: ^/api/produits/\d+$, roles: ROLE_USER, methods: [GET] }
        - { path: ^/api/produits/categorie, roles: ROLE_USER, methods: [GET] }
        - { path: ^/api/produits/search, roles: ROLE_USER, methods: [GET] }
        
        # Modification des produits - admins seulement
        - { path: ^/api/produits, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        
        # Toutes les autres routes API nécessitent une authentification
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10